version: "3.7"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./MServerData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= MServer
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - network-backend
    
  
  backend:
    build: ./media-server
    expose:
      - ${APP_BACKEND_PORT}
    environment:
      APP_SERVER_PORT : ${APP_BACKEND_PORT}
      DB_CONNECTION : ${DB_CONNECTION_STRING}
    ports:
      - ${APP_BACKEND_PORT}:${APP_BACKEND_PORT}
    depends_on:
      - db
    networks:
      - network-backend
      - network-frontend 
  
  frontend:
    build: ./frontend
    expose:
      - "${APP_CLIENT_PORT}"
    environment:
      BACKEND_URL: http://backend:${APP_BACKEND_PORT}/
    depends_on:
      - backend
    ports:
      - "${APP_CLIENT_PORT}:${APP_CLIENT_PORT}"
    networks:
      - network-frontend
networks:
  network-backend:
  network-frontend:
  



    
    