version: "3.7"

services:
  db:
    container_name : db
    image: mongo:latest
    restart: always
    volumes:
      - ./MServerData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= MServer
    ports:
      - ${DB_PORT}:${DB_PORT}
    
  
  backend:
    container_name: backend
    build: ./media-server
    expose:
      - ${APP_BACKEND_PORT}
    environment:
      APP_SERVER_PORT : ${APP_BACKEND_PORT}
      DB_CONNECTION : ${DB_CONNECTION_STRING}
    ports:
      - ${APP_BACKEND_PORT}:${APP_BACKEND_PORT}
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - ${APP_CLIENT_PORT}
    environment:
      BACKEND_URL: http://backend:${APP_BACKEND_PORT}/
    depends_on:
      - backend
    ports:
      - ${APP_CLIENT_PORT}:${APP_CLIENT_PORT}

  



    
    