version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./MServerData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= MServer
    ports:
      - 27017:27017
    


    
    