version: "3.7"

services:
  db:
    container_name : db
    image: mongo:latest
    restart: always
    volumes:
      - ./MServerData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= MServer
    ports:
      - 27017:27017

  



    
    